name: Publish

on:
  push:
    tags: [ v* ]

env:
  DOTNET_VERSION: 6.0.x

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup Version
      id: setup_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Publish Function app
      run: dotnet publish -c Release -r win-x86 --self-contained false -o ./dist -p:Version=${{ steps.setup_version.outputs.VERSION }} ContainerApps.Acmebot

    - name: Zip Function app
      run: 7z a -mx=9 latest.zip ./dist/*

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: latest
        path: ./latest.zip

  upload:
    environment: production
    needs: publish
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: latest

    - name: Upload to Blob
      run: |
        az storage blob upload --auth-mode login -f latest.zip --account-name stacmebotprod -c containerapps-acmebot -n v1/latest.zip --overwrite
        az storage blob upload --auth-mode login -f latest.zip --account-name stacmebotprod -c containerapps-acmebot -n v1/${{ steps.setup_version.outputs.VERSION }}.zip --overwrite
